const {test}=require('node:test');const assert=require('node:assert/strict');const core=require('../../code_sandbox_light_git_fe61910d_1781185357/js/bpa-audit-core.js');
const cns='700000000000005';
function line(over={}){const r={tipo:'03',cnes:'1234567',comp:'202608',cns,cbo:'225125',dt:'20260815',seq:'01',proc:'0301010072',sexo:'M',cid:'A000',idade:'030',qtd:'000001',nasc:'19960801',servico:'',classificacao:'',...over};const a=Array(349).fill(' ');const put=(pos,value)=>[...value].forEach((c,i)=>a[pos-1+i]=c);put(1,r.tipo);put(3,r.cnes);put(10,r.comp);put(16,r.cns);put(31,r.cbo);put(37,r.dt);put(45,'001');put(48,r.seq);put(50,r.proc);put(75,r.sexo);put(82,r.cid);put(86,r.idade);put(89,r.qtd);put(110,'BPA');put(143,r.nasc);put(160,r.servico);put(163,r.classificacao);return a.join('');}
function file(rows){const a=Array(130).fill(' ');const put=(p,v)=>[...v].forEach((c,i)=>a[p-1+i]=c);put(1,'01#BPA#');put(8,'202608');put(14,String(rows.length).padStart(6,'0'));put(20,'000001');const sum=rows.reduce((s,r)=>s+BigInt(r.slice(49,59))+BigInt(r.slice(88,94)),0n);put(26,String(Number(sum%1111n)+1111));return a.join('')+'\r\n'+rows.join('\r\n')+'\r\n';}
function bases(){return {'202608':{cnes:{competencia:'202608',oficial:true,completo:true,cobertura:{profissionais:true,servicos:true,habilitacoes:true},estabelecimentos:[{cnes:'1234567',profissionais:[{cns,cbo:'225125',ativo:true}],servicos:[],habilitacoes:[]}]},sigtap:{competencia:'202608',oficial:true,completo:true,cobertura:{cbos:true,cids:true,servicos:true,habilitacoes:true,instrumentos:true,regrasComplementares:true},procedimentos:{'0301010072':{cbos:['225125'],cids:['A000'],servicos:[],habilitacoes:[],instrumentos:['02'],sexo:'I',idade:{min:0,max:130,unidade:'anos'},limiteQuantidade:{max:2,escopo:'registro'},vl_sa:'10,50',regrasComplementares:[]}}}}};}
const run=(over={},b=bases())=>{const parsed=core.parse(file([line(over)]));if(Object.prototype.hasOwnProperty.call(over,'cbo'))parsed.records[0].cbo=over.cbo;return core.audit(parsed,b);};
test('leitura posicional do BPA-I preserva CNS, CBO, procedimento, quantidade e linha física',()=>{const r=core.parse(file([line()])).records[0];assert.equal(r.cnsProfissional,cns);assert.equal(r.procedimento,'0301010072');assert.equal(r.quantidade,'000001');assert.equal(r.linha,2);assert.equal(r.nascimento,'19960801');});
test('arquivo real completo sem achados tem resultado conforme',()=>assert.equal(run().status,'CONFORME'));
test('não inventa registros em arquivo vazio',()=>{const r=core.audit('',{});assert.equal(r.totalLinhas,0);assert.notEqual(r.status,'CONFORME');});
test('base de outra competência nunca aprova vínculo',()=>{const b=bases();b['202608'].cnes.competencia='202607';const r=run({},b);assert.equal(r.status,'INCONCLUSIVO');assert.ok(r.findings.some(f=>f.regra==='BASE_CNES'));});
test('CNS inexistente com dígito válido é apontado no vínculo',()=>assert.ok(run({cns:'700000000000016'}).findings.some(f=>f.regra==='VINCULO_PROFISSIONAL'&&f.status==='NAO_CONFORME')));
test('dígito CNS inválido é diagnosticado',()=>assert.ok(run({cns:'700000000000000'}).findings.some(f=>f.regra==='CNS_PROFISSIONAL')));
test('CBO é confrontado somente com a relação exata do procedimento',()=>{const r=run({cbo:'225250'});assert.equal(r.findings.some(f=>f.regra==='VINCULO_PROFISSIONAL'),false);assert.ok(r.findings.some(f=>f.regra==='CBO_SIGTAP'));});
test('relação faltante não equivale a compatibilidade',()=>{const b=bases();delete b['202608'].sigtap.procedimentos['0301010072'].cbos;assert.equal(run({},b).status,'INCONCLUSIVO');});
test('Regra 1 confirma CNS da mesma unidade sem exigir status ou CBO CNES',()=>{const b=bases();b['202608'].cnes.estabelecimentos[0].profissionais=[{cns,cbo:'999999',situacao:'DESLIGADO',compDesativacao:'202607'}];assert.equal(run({},b).findings.some(f=>f.regra==='VINCULO_PROFISSIONAL'),false);});
test('Regra 1 rejeita CNS somente em outro CNES e mapa global',()=>{const b=bases();b['202608'].cnes.estabelecimentos[0].profissionais=[];b['202608'].cnes.mapaVinculos={[`cns_${cns}`]:{cnes:'7654321'}};assert.equal(run({},b).findings.find(f=>f.regra==='VINCULO_PROFISSIONAL').status,'NAO_CONFORME');});
test('CBO exige seis dígitos numéricos',()=>{for(const cbo of ['2231A1','12345','1234567',''])assert.equal(run({cbo}).findings.find(f=>f.regra==='CBO_FORMATO').status,'NAO_CONFORME');});
test('Regra 4 depende somente do par SIGTAP',()=>{const b=bases();b['202608'].sigtap.procedimentos['0301010072'].servicos=[{servico:'121',classificacao:'003'}];b['202608'].cnes.cobertura.servicos=false;const result=run({servico:'121',classificacao:'003'},b);assert.equal(result.findings.some(f=>['SERVICO_CNES','HABILITACAO'].includes(f.regra)),false);});
test('CID incompatível é apontado',()=>assert.ok(run({cid:'B000'}).findings.some(f=>f.regra==='CID')));
test('idade zero não vira idade adulta',()=>{const r=run({idade:'000',nasc:'20260801'});assert.equal(r.status,'CONFORME');});
test('quantidade zero é inválida e não vira um',()=>assert.ok(run({qtd:'000000'}).findings.some(f=>f.regra==='QUANTIDADE')));
test('limite usa regra importada, não teto fixo dez',()=>assert.ok(run({qtd:'000003'}).findings.some(f=>f.regra==='LIMITE_QUANTIDADE')));
test('base sem origem validada não aprova',()=>{const b=bases();b['202608'].sigtap.oficial=false;assert.equal(run({},b).status,'INCONCLUSIVO');});
test('atributo desconhecido torna parecer inconclusivo',()=>{const b=bases();b['202608'].sigtap.procedimentos['0301010072'].regrasComplementares=[{tipo:'desconhecida'}];assert.equal(run({},b).status,'INCONCLUSIVO');});
test('duplicidade gera alerta, sem exclusão e sem aprovação',()=>{const r=core.audit(file([line(),line()]),bases());assert.equal(r.totalLinhas,2);assert.equal(r.alertas,1);assert.equal(r.status,'INCONCLUSIVO');});
test('malformação não some da auditoria',()=>{const r=core.audit(file([line()])+'XYZ',bases());assert.ok(r.findings.some(f=>f.regra==='ESTRUTURA'));assert.equal(r.status,'NAO_CONFORME');});
test('BPA-C lê posições próprias e não exige CNS individual',()=>{const raw='02'+'1234567'+'202608'+'225125'+'001'+'01'+'0301010072'+'030'+'000120'+'BPA';const r=core.parse(raw).records[0];assert.equal(r.procedimento,'0301010072');assert.equal(r.quantidade,'000120');assert.equal(r.cnsProfissional,'');const result=core.audit({records:[r],issues:[]},bases());assert.equal(result.checks.CNS_PROFISSIONAL.NAO_APLICAVEL,1);assert.equal(result.checks.LIMITE_QUANTIDADE.NAO_APLICAVEL,1);});
module.exports={file,line,bases};

test('CPF válido não recebe erro de dígito; CPF inválido recebe',()=>{for(const [cpf,valid]of [['12345678909',true],['12345678900',false]]){let l=line();l=l.slice(0,338)+cpf;const r=core.audit(file([l]),bases());assert.equal(r.findings.some(f=>f.regra==='CPF_PACIENTE'),!valid);}});
test('idade SIGTAP em meses é calculada na data exata',()=>{const b=bases();b['202608'].sigtap.procedimentos['0301010072'].idade={min:360,max:360,unidade:'meses'};assert.equal(run({},b).status,'CONFORME');b['202608'].sigtap.procedimentos['0301010072'].idade.max=359;assert.ok(run({},b).findings.some(f=>f.regra==='FAIXA_ETARIA'));});
test('atributo CPF não obriga campo ausente do layout BPA-C',()=>{const b=bases();b['202608'].sigtap.procedimentos['0301010072'].regrasComplementares=[{tipo:'campoObrigatorio',campo:'cpfPaciente'}];const r=core.parse('02'+'1234567'+'202608'+'225125'+'001'+'01'+'0301010072'+'030'+'000120'+'BPA').records[0];assert.equal(core.audit({records:[r],issues:[]},b).checks.ATRIBUTO_COMPLEMENTAR.NAO_APLICAVEL,1);});
test('valor SA é calculado pela quantidade e preservado no diagnóstico',()=>{const r=run();assert.equal(r.valorReferenciaSa,10.5);assert.equal(r.registrosValorizados,1);assert.equal(r.registrosSemValor,0);assert.equal(r.checks.VALOR_SIGTAP.CONFORME,1);});
test('valor SA zero é valor conhecido e não fica como ausente',()=>{const b=bases();b['202608'].sigtap.procedimentos['0301010072'].vl_sa='0';const r=run({},b);assert.equal(r.valorReferenciaSa,0);assert.equal(r.registrosValorizados,1);assert.equal(r.registrosSemValor,0);});
test('extensão de até dois caracteres não cria falso erro de estrutura',()=>{const raw='02'+'1234567'+'202608'+'225125'+'001'+'01'+'0301010072'+'030'+'000120'+'BPA'+'  ';const r=core.parse(file([raw]));assert.equal(r.records[0].layoutKnown,true);assert.equal(r.issues.some(i=>/Comprimento/.test(i.mensagem)),false);});
