const {test}=require('node:test');const assert=require('node:assert/strict');const api=require('../../code_sandbox_light_git_fe61910d_1781185357/js/sigtap-audit-api.js');
const code='0301010072',cm='202608';
test('paginação recupera todas as ocupações da competência',async()=>{let calls=0;const rows=await api.relation(code,cm,'ocupacoes',async url=>({ok:true,json:async()=>{calls++;return {count:2,competencia:cm,results:[{ocupacao:{co_ocupacao:calls===1?'225125':'225250'}}],next:calls===1?'https://sigtap-api.vercel.app/api/v1/sigtap/procedimentos/'+code+'/ocupacoes/?competencia='+cm+'&page=2':null};}}));assert.equal(rows.length,2);assert.equal(calls,2);});
test('competência divergente da API é rejeitada',async()=>{await assert.rejects(api.relation(code,cm,'cids',async()=>({ok:true,json:async()=>({competencia:'202609',results:[],count:0,next:null})})),/competência/);});
test('paginação incompleta não vira lista vazia válida',async()=>{await assert.rejects(api.relation(code,cm,'cids',async()=>({ok:true,json:async()=>({competencia:cm,results:[],count:10,next:null})})),/incompleta/);});
test('paginação para outro servidor é rejeitada',async()=>{await assert.rejects(api.relation(code,cm,'cids',async()=>({ok:true,json:async()=>({competencia:cm,results:[],count:0,next:'https://example.com/'})})),/inconsistente/);});
test('API recebe somente procedimento público e competência; não envia identificadores do BPA',async()=>{const urls=[];await api.load([{competencia:cm,procedimento:code,cnsProfissional:'700000000000005',cpfPaciente:'12345678909'}],async url=>{urls.push(url);return {ok:false,status:503};});assert.equal(urls.length,1);assert.ok(!urls[0].includes('700000000000005'));assert.ok(!urls[0].includes('12345678909'));});
test('valor SA da resposta SIGTAP é convertido para número e marcado como conhecido',async()=>{const result=await api.load([{competencia:cm,procedimento:code}],async url=>{const u=new URL(url);if(u.pathname.endsWith(code+'/'))return {ok:true,json:async()=>({competencia:cm,co_procedimento:code,vl_sa:'12,34',vl_sh:'0',vl_sp:'0',qt_maxima_execucao:9999})};return {ok:true,json:async()=>({competencia:cm,results:[],count:0,next:null})};});const proc=result.bases[cm].procedimentos[code];assert.equal(proc.valorSa,12.34);assert.equal(proc.valorSaConhecido,true);});
test('detalhes informativos (PMAE, modalidade) e regras de financiamento/compatibilidade não viram exigência verificável',async()=>{const result=await api.load([{competencia:cm,procedimento:code}],async url=>{const u=new URL(url);if(u.pathname.endsWith(code+'/'))return {ok:true,json:async()=>({competencia:cm,co_procedimento:code,vl_sa:'10,00',qt_maxima_execucao:9999})};if(u.pathname.includes('/detalhes/'))return {ok:true,json:async()=>({competencia:cm,count:4,next:null,results:[{detalhe:{co_detalhe:'012',no_detalhe:'Exige idade no BPA (Consolidado)'}},{detalhe:{co_detalhe:'053',no_detalhe:'Programa Mais Acesso a Especialistas (PMAE)'}},{detalhe:{co_detalhe:'058',no_detalhe:'Obrigatório CPF'}},{detalhe:{co_detalhe:'060',no_detalhe:'Componente Complementar - Modalidade 3'}}]})};if(u.pathname.includes('/regras-condicionadas/'))return {ok:true,json:async()=>({competencia:cm,count:1,next:null,results:[{regra_condicionada:{co_regra_condicionada:'0014',ds_regra_condicionada:'CONDICIONA O TIPO DE FINANCIAMENTO EM MAC'}}]})};if(u.pathname.includes('/compativeis/'))return {ok:true,json:async()=>({competencia:cm,count:1,next:null,results:[{tp_compatibilidade:'X',procedimento_compativel:{co_procedimento:'0301010073'}}]})};return {ok:true,json:async()=>({competencia:cm,results:[],count:0,next:null})};});const proc=result.bases[cm].procedimentos[code];assert.equal(proc.cobertura.regrasComplementares,true);const tipos=Object.fromEntries(proc.regrasComplementares.map(r=>[r.codigo||r.campo,r.tipo]));assert.equal(tipos['058'],'campoObrigatorio');assert.equal(proc.regrasComplementares.find(r=>r.campo==='cpfPaciente').campo,'cpfPaciente');assert.equal(tipos['012'],'idadeBpaC');assert.equal(tipos['053'],'informativo');assert.equal(tipos['060'],'informativo');assert.equal(tipos['0014'],'informativo');assert.ok(proc.regrasComplementares.some(r=>r.tipo==='informativo'&&/Compatibilidade/.test(r.fonte)));});
