const fs = require('fs');
const path = require('path');

const basePath = path.join(__dirname, '../code_sandbox_light_git_fe61910d_1781185357');

const replacements = [
    // Multi-byte corruptions
    ['CONCILIA?fO', 'CONCILIAÇÃO'],
    ['CONFIRMA?fO', 'CONFIRMAÇÃO'],
    ['PRODU?fO', 'PRODUÇÃO'],
    ['SE?fO', 'SEÇÃO'],

    // Specific phrases and titles
    ['Superintendncia de Controle, Avaliao, Auditoria e Regulao', 'Superintendência de Controle, Avaliação, Auditoria e Regulação'],
    ['Inteligncia para Gesto da Mdia e Alta Complexidade Ambulatorial', 'Inteligência para Gestão da Média e Alta Complexidade Ambulatorial'],
    ['CNES & Vnculos', 'CNES & Vínculos'],
    ['Conciliao FNS', 'Conciliação FNS'],
    ['Produo Ambulatorial', 'Produção Ambulatorial'],
    ['Produes BPA', 'Produções BPA'],
    ['Eficincia', 'Eficiência'],
    ['EFICINCIA', 'EFICIÊNCIA'],
    ['Regulao', 'Regulação'],
    ['REGULAO', 'REGULAÇÃO'],
    ['Relatrios', 'Relatórios'],
    ['RELATRIOS', 'RELATÓRIOS'],
    ['Relatrio', 'Relatório'],
    ['ADMINISTRAO', 'ADMINISTRAÇÃO'],
    ['Administrao', 'Administração'],
    ['Usurios', 'Usuários'],
    ['USURIOS', 'USUÁRIOS'],
    ['Usurio', 'Usuário'],
    ['USURIO', 'USUÁRIO'],
    ['MULTI-MUNICPIO', 'MULTI-MUNICÍPIO'],
    ['Multi-Municpio', 'Multi-Município'],
    ['UF/MUNICPIO', 'UF/MUNICÍPIO'],
    ['MUNICPIO', 'MUNICÍPIO'],
    ['Municpio', 'Município'],
    ['Municpios', 'Municípios'],
    ['municpios', 'municípios'],
    ['municpio', 'município'],

    ['HOSPITAL MARIA SOCORRO BRANDO', 'HOSPITAL MARIA SOCORRO BRANDÃO'],
    ['LABORATRIO CENTRAL DR. COELHO DIAS', 'LABORATÓRIO CENTRAL DR. COELHO DIAS'],
    ['POLICLNICA DE BACABAL', 'POLICLÍNICA DE BACABAL'],
    ['CENTRAL DE REGULAO', 'CENTRAL DE REGULAÇÃO'],
    ['VIGILNCIA SANITRIA', 'VIGILÂNCIA SANITÁRIA'],
    ['MOTOLNCIA BACABAL', 'MOTOLÂNCIA BACABAL'],

    // Common words
    ['Produes', 'Produções'],
    ['produes', 'produções'],
    ['PRODUES', 'PRODUÇÕES'],
    ['Produo', 'Produção'],
    ['produo', 'produção'],
    ['PRODUO', 'PRODUÇÃO'],
    ['Atribuies', 'Atribuições'],
    ['atribuies', 'atribuições'],
    ['Atribuio', 'Atribuição'],
    ['atribuio', 'atribuição'],
    ['Atribudo', 'Atribuído'],
    ['atribudo', 'atribuído'],
    ['Atribuda', 'Atribuída'],
    ['atribuda', 'atribuída'],
    ['Atribudas', 'Atribuídas'],
    ['atribudas', 'atribuídas'],
    ['Atualizao', 'Atualização'],
    ['atualizao', 'atualização'],
    ['Avaliao', 'Avaliação'],
    ['avaliao', 'avaliação'],
    ['AVALIAO', 'AVALIAÇÃO'],
    ['Avanados', 'Avançados'],
    ['avanados', 'avançados'],
    ['Aes', 'Ações'],
    ['aes', 'ações'],
    ['AES', 'AÇÕES'],
    ['Ao', 'Ação'],
    ['ao', 'ação'],
    ['AO', 'AÇÃO'],
    ['Boto', 'Botão'],
    ['boto', 'botão'],
    ['Competncias', 'Competências'],
    ['competncias', 'competências'],
    ['Competncia', 'Competência'],
    ['competncia', 'competência'],
    ['COMPETNCIA', 'COMPETÊNCIA'],
    ['Concluso', 'Conclusão'],
    ['concluso', 'conclusão'],
    ['Conexo', 'Conexão'],
    ['conexo', 'conexão'],
    ['Configuraes', 'Configurações'],
    ['configuraes', 'configurações'],
    ['Configurao', 'Configuração'],
    ['configurao', 'configuração'],
    ['Contedo', 'Conteúdo'],
    ['contedo', 'conteúdo'],
    ['Crtica', 'Crítica'],
    ['crtica', 'crítica'],
    ['Cpia', 'Cópia'],
    ['cpia', 'cópia'],
    ['Destinatrios', 'Destinatários'],
    ['destinatrios', 'destinatários'],
    ['Destinatrio', 'Destinatário'],
    ['destinatrio', 'destinatário'],
    ['Dicionrios', 'Dicionários'],
    ['dicionrios', 'dicionários'],
    ['Disponveis', 'Disponíveis'],
    ['disponveis', 'disponíveis'],
    ['Disponvel', 'Disponível'],
    ['disponvel', 'disponível'],
    ['Distribuio', 'Distribuição'],
    ['distribuio', 'distribuição'],
    ['Divergncias', 'Divergências'],
    ['divergncias', 'divergências'],
    ['Divergncia', 'Divergência'],
    ['divergncia', 'divergência'],
    ['EVOLUO', 'EVOLUÇÃO'],
    ['Evoluo', 'Evolução'],
    ['evoluo', 'evoluçâo'],
    ['EXCLUSO', 'EXCLUSÃO'],
    ['Excluso', 'Exclusão'],
    ['excluso', 'exclusão'],
    ['Execuo', 'Execução'],
    ['execuo', 'execução'],
    ['Exportao', 'Exportação'],
    ['exportao', 'exportação'],
    ['GRFICO', 'GRÁFICO'],
    ['Grficos', 'Gráficos'],
    ['grficos', 'gráficos'],
    ['Grfico', 'Gráfico'],
    ['grfico', 'gráfico'],
    ['Gesto', 'Gestão'],
    ['gesto', 'gestão'],
    ['GESTO', 'GESTÃO'],
    ['HISTRICO', 'HISTÓRICO'],
    ['Histrico', 'Histórico'],
    ['histrico', 'histórico'],
    ['Identificao', 'Identificação'],
    ['identificao', 'identificação'],
    ['Importaes', 'Importações'],
    ['importaes', 'importações'],
    ['Importao', 'Importação'],
    ['importao', 'importação'],
    ['Imprimvel', 'Imprimível'],
    ['imprimvel', 'imprimível'],
    ['Lgica', 'Lógica'],
    ['lgica', 'lógica'],
    ['Magntico', 'Magnético'],
    ['magntico', 'magnético'],
    ['Mdio', 'Médio'],
    ['mdio', 'médio'],
    ['Mdulos', 'Módulos'],
    ['mdulos', 'módulos'],
    ['Mdulo', 'Módulo'],
    ['mdulo', 'módulo'],
    ['MDULO', 'MÓDULO'],
    ['Mnima', 'Mínima'],
    ['mnima', 'mínima'],
    ['Ms', 'Mês'],
    ['ms', 'mês'],
    ['Mvel', 'Móvel'],
    ['mvel', 'móvel'],
    ['Notificao', 'Notificação'],
    ['notificao', 'notificação'],
    ['No', 'Não'],
    ['no', 'não'],
    ['OPO', 'OPÇÃO'],
    ['Opo', 'Opção'],
    ['opo', 'opção'],
    ['ORAMENTRIA', 'ORÇAMENTÁRIA'],
    ['oramentria', 'orçamentária'],
    ['Observatrio', 'Observatório'],
    ['observatrio', 'observatório'],
    ['Observaes', 'Observações'],
    ['observaes', 'observações'],
    ['Ocorrncias', 'Ocorrências'],
    ['ocorrncias', 'ocorrências'],
    ['Ocupaes', 'Ocupações'],
    ['ocupaes', 'ocupações'],
    ['PADRO', 'PADRÃO'],
    ['Padro', 'Padrão'],
    ['padro', 'padrão'],
    ['PROFISSES', 'PROFISSÕES'],
    ['Profisses', 'Profissões'],
    ['profisses', 'profissões'],
    ['Profisso', 'Profissão'],
    ['profisso', 'profissão'],
    ['Parmetros', 'Parâmetros'],
    ['parmetros', 'parâmetros'],
    ['Permisses', 'Permissões'],
    ['permisses', 'permissões'],
    ['PERMISSO', 'PERMISSÃO'],
    ['Permisso', 'Permissão'],
    ['permisso', 'permissão'],
    ['Perodo', 'Período'],
    ['perodo', 'período'],
    ['Prvia', 'Prévia'],
    ['prvia', 'prévia'],
    ['Pblica', 'Pública'],
    ['pblica', 'pública'],
    ['REFERNCIA', 'REFERÊNCIA'],
    ['referncia', 'referência'],
    ['RESPONSVEIS', 'RESPONSÁVEIS'],
    ['Responsveis', 'Responsáveis'],
    ['responsveis', 'responsáveis'],
    ['RESPONSVEL', 'RESPONSÁVEL'],
    ['Responsvel', 'Responsável'],
    ['responsvel', 'responsável'],
    ['Retrtil', 'Retrátil'],
    ['retrtil', 'retrátil'],
    ['RPIDO', 'RÁPIDO'],
    ['rpido', 'rápido'],
    ['SELEO', 'SELEÇÃO'],
    ['seleo', 'seleção'],
    ['SEO', 'SEÇÃO'],
    ['Sees', 'Seções'],
    ['sees', 'seções'],
    ['Seo', 'Seção'],
    ['seo', 'seção'],
    ['Sade', 'Saúde'],
    ['sade', 'saúde'],
    ['Secretrio', 'Secretário'],
    ['secretrio', 'secretário'],
    ['Segurana', 'Segurança'],
    ['segurana', 'segurança'],
    ['Servios', 'Serviços'],
    ['servios', 'serviços'],
    ['Servio', 'Serviço'],
    ['servio', 'serviço'],
    ['Sntese', 'Síntese'],
    ['sntese', 'síntese'],
    ['UTILIZAO', 'UTILIZAÇÃO'],
    ['Utilizao', 'Utilização'],
    ['utilizao', 'utilização'],
    ['Unitrio', 'Unitário'],
    ['unitrio', 'unitário'],
    ['VISO', 'VISÃO'],
    ['Viso', 'Visão'],
    ['viso', 'visão'],
    ['Voc', 'Você'],
    ['voc', 'você'],
    ['Vnculos', 'Vínculos'],
    ['vnculos', 'vínculos'],
    ['Vnculo', 'Vínculo'],
    ['vnculo', 'vínculo'],
    ['aparecer', 'aparecerá'],
    ['aprovao', 'aprovação'],
    ['aps', 'após'],
    ['autenticao', 'autenticação'],
    ['automticos', 'automáticos'],
    ['automtica', 'automática'],
    ['AUTOMTICA', 'AUTOMÁTICA'],
    ['cabealho', 'cabeçalho'],
    ['Cabealho', 'Cabeçalho'],
    ['conferncia', 'conferência'],
    ['demonstrao', 'demonstração'],
    ['eficincia', 'eficiência'],
    ['espao', 'espaço'],
    ['estratgicos', 'estratégicos'],
    ['exerccio', 'exercício'],
    ['ficaro', 'ficarão'],
    ['gerao', 'geração'],
    ['impresso', 'impressão'],
    ['includo', 'incluído'],
    ['ir', 'irá'],
    ['J', 'Já'],
    ['j', 'já'],
    ['lquido', 'líquido'],
    ['nmeros', 'números'],
    ['relatrio', 'relatório'],
    ['relatrios', 'relatórios'],
    ['sero', 'serão'],
    ['ser', 'será'],
    ['S', 'Só'],
    ['s', 'só'],
    ['So', 'São'],
    ['so', 'são'],
    ['tecnolgico', 'tecnológico'],
    ['tendncias', 'tendências'],
    ['Tendncia', 'Tendência'],
    ['vdeo', 'vídeo'],
    ['ltimo', 'Último'],
    ['ltimos', 'últimos'],
    ['LTIMO', 'ÚLTIMO'],
    ['rbita', 'órbita'],
    ['Cdigo', 'Código'],
    ['cdigo', 'código'],
    ['DESCRIO', 'DESCRIÇÃO'],
    ['Descrio', 'Descrição'],
    ['descrio', 'descrição'],
    ['Mdia', 'Média'],
    ['mdia', 'média'],
    ['Variao', 'Variação'],
    ['variao', 'variação'],
    ['Projeo', 'Projeção'],
    ['projeo', 'projeção'],
    ['PROJEO', 'PROJEÇÃO'],
    ['SITUAO', 'SITUAÇÃO'],
    ['Situao', 'Situação'],
    ['situao', 'situação'],
    ['Diferena', 'Diferença'],
    ['diferena', 'diferença'],
    ['Participao', 'Participação'],
    ['participao', 'participação'],
    ['Maro', 'Março'],
    ['maro', 'março'],
    ['PENDNCIAS', 'PENDÊNCIAS'],
    ['Pendncias', 'Pendências'],
    ['pendncias', 'pendências'],
    ['Pendncia', 'Pendência'],
    ['pendncia', 'pendência'],
    ['PERSISTNCIA', 'PERSISTÊNCIA'],
    ['POLICLNICA', 'POLICLÍNICA'],
    ['PRPRIO', 'PRÓPRIO'],
    ['prprias', 'próprias'],
    ['prprio', 'próprio'],
    ['RENDERIZAO', 'RENDERIZAÇÃO'],
    ['SANITRIA', 'SANITÁRIA'],
    ['Transio', 'Transição'],
    ['transio', 'transição'],
    ['VALIDAO', 'VALIDAÇÃO'],
    ['validao', 'validação'],
    ['VIGILNCIA', 'VIGILÂNCIA'],
    ['amigvel', 'amigável'],
    ['contm', 'contém'],
    ['especficas', 'específicas'],
    ['especficos', 'específicos'],
    ['estar', 'estará'],
    ['estatsticas', 'estatísticas'],
    ['esto', 'estão'],
    ['est', 'está'],
    ['EST', 'ESTÁ'],
    ['exigncia', 'exigência'],
    ['explicao', 'explicação'],
    ['explcita', 'explícita'],
    ['extenso', 'extensão'],
    ['implantao', 'implantação'],
    ['indisponvel', 'indisponível'],
    ['instruo', 'instrução'],
    ['invlida', 'inválida'],
    ['invlido', 'inválido'],
    ['lanado', 'lançado'],
    ['necessrias', 'necessárias'],
    ['Necessria', 'Necessária'],
    ['possvel', 'possível'],
    ['pgina', 'página'],
    ['remoo', 'remoção'],
    ['visualizao', 'visualização'],
    ['NICA', 'ÚNICA'],
    ['nico', 'único'],
    ['nica', 'única'],
    ['cone', 'ícone'],
    ['s', 'às'],
    [' ', 'à '],
    ['  ', ' — ']
];

function fixFile(filePath) {
    let content = fs.readFileSync(filePath, 'utf8');
    let initialCount = 0;
    for (let i = 0; i < content.length; i++) if (content.charCodeAt(i) === 0xFFFD) initialCount++;

    for (const [from, to] of replacements) {
        content = content.split(from).join(to);
    }

    let finalCount = 0;
    for (let i = 0; i < content.length; i++) if (content.charCodeAt(i) === 0xFFFD) finalCount++;

    fs.writeFileSync(filePath, content, 'utf8');
    console.log(`${path.basename(filePath)}: reduced from ${initialCount} to ${finalCount} broken characters.`);
}

fixFile(path.join(basePath, 'index.html'));
fixFile(path.join(basePath, 'js/bpa-module.js'));
